### PR TITLE
Initial

### PR DESCRIPTION
**Pull request by mendozagit**
test

### CODE REVIEW

**Comment by gfoidl** [comment]
@mendozagit can you please provide some information what this PR should do?

**Comment by mendozagit** [comment]
Hi @gfoidl, you know what. I've sent this PR by mistake. Apologies for that feel free to delete it. I appreciate your time!

**Comment by gfoidl** [comment]
@mendozagit no problem. I don't have to rights to close the PR, but you can close the PR here.
PRs can't be deleted anyway, as that would change the history of the project, thus GitHub doesn't provide a option for this.

**Comment by mycroes** [comment]
@gfoidl Are you interested in co-maintaining the project, or would that only be a burden? I appreciate your help and knowledge, I trust your integrity, so if it's up to me then I'd welcome you aboard.

**Comment by mycroes** [comment]
@mendozagit Closing per your request, good luck on your project!

**Comment by gfoidl** [comment]
@mycroes thanks ❤️
Yes I'm interested. I'm stepping by almost daily, try to help where possible, so that wouldn't be any burden at all.

**Comment by mendozagit** [comment]
@mycroes @gfoidl, thanks guys!

**Comment by gfoidl** [comment]
@mycroes thanks for the invitation 😃
But I can't close issues, etc. Can you please check if there's another setting needed?

**Comment by mycroes** [comment]
@gfoidl for sure I needed to do more, not sure if I could do that before you accepted the invite. You now have the maintainer role in this repository.

Regards,
Michael

**Comment by gfoidl** [comment]
Perfect. Thank you very much! (Also in the trust you gave me with that role)

**Pull request closed without merging**
