### PR TITLE
Support asynchronous reading and writing from the plc

### PR DESCRIPTION
**Pull request by thomasbargetz**
This change enables asynchronous reading and writing from the plc. I've made every original method async and created a synchronous wrapper for them to avoid breaking the API.

I didn't upgrade the target framework (still 3.5). So I had to add 2 dependencies to support async, await and Task.

### CODE REVIEW

**Comment by mesta1** [comment]
Need to have a look at this.

**Comment by thomasbargetz** [comment]
I've merged in the current master branch. Let me know if you would like a different kind of asynchronous implementation.

**Comment by thomasbargetz** [comment]
@mesta1 any complains?

**Comment by mesta1** [comment]
Ah sorry, thanks for reminding me. I didn't see any problem.

**Comment by mesta1** [comment]
I can't build... I'm using VS 2013. Can you have a look ? I'm considering to move to .Net 4.5.2, due to the fact that VS2015 and VS2017 are free.

Here the errors

PLC.cs(124,19): error CS0121: The call is ambiguous between the following methods or properties: 'System.Threading.Tasks.TaskFactory.FromAsync(System.IAsyncResult, System.Action<System.IAsyncResult>)' and 'System.Threading.Tasks.TaskFactory.FromAsync<int>(System.IAsyncResult, System.Func<System.IAsyncResult,int>)' [C:\projects\s7netplus\S7.Net\S7.Net.csproj]
PLC.cs(124,103): error CS0407: 'int System.Net.Sockets.Socket.EndSend(System.IAsyncResult)' has the wrong return type [C:\projects\s7netplus\S7.Net\S7.Net.csproj]
PLC.cs(129,26): error CS0121: The call is ambiguous between the following methods or properties: 'System.Threading.Tasks.TaskFactory.FromAsync(System.IAsyncResult, System.Action<System.IAsyncResult>)' and 'System.Threading.Tasks.TaskFactory.FromAsync<int>(System.IAsyncResult, System.Func<System.IAsyncResult,int>)' [C:\projects\s7netplus\S7.Net\S7.Net.csproj]
PLC.cs(129,124): error CS0407: 'int System.Net.Sockets.Socket.EndReceive(System.IAsyncResult)' has the wrong return type [C:\projects\s7netplus\S7.Net\S7.Net.csproj]
PLC.cs(129,20): error CS0029: Cannot implicitly convert type 'void' to 'int' [C:\projects\s7netplus\S7.Net\S7.Net.csproj]
PLC.cs(138,21): error CS0121: The call is ambiguous between the following methods or properties: 'System.Threading.Tasks.TaskFactory.StartNew(System.Action)' and 'System.Threading.Tasks.TaskFactory.StartNew<System.Threading.Tasks.Task<S7.Net.ErrorCode>>(System.Func<System.Threading.Tasks.Task<S7.Net.ErrorCode>>)' [C:\projects\s7netplus\S7.Net\S7.Net.csproj]
PLC.cs(138,43): error CS0407: 'System.Threading.Tasks.Task<S7.Net.ErrorCode> S7.Net.Plc.OpenAsync()' has the wrong return type [C:\projects\s7netplus\S7.Net\S7.Net.csproj]
PLC.cs(138,21): error CS1928: 'System.Threading.Tasks.Task' does not contain a definition for 'Unwrap' and the best extension method overload 'System.Threading.Tasks.TaskExtensions.Unwrap(System.Threading.Tasks.Task<System.Threading.Tasks.Task>)' has some invalid arguments [C:\projects\s7netplus\S7.Net\S7.Net.csproj]
PLC.cs(138,21): error CS1929: Instance argument: cannot convert from 'System.Threading.Tasks.Task' to 'System.Threading.Tasks.Task<System.Threading.Tasks.Task>' [C:\projects\s7netplus\S7.Net\S7.Net.csproj]

https://ci.appveyor.com/project/mesta1/s7netplus

**Comment by mesta1** [comment]
Or maybe I just upgrade the VS version that I use to build, pack all in NuGet, and it will still support .Net 3.5. Need to make some tests.

**Comment by mesta1** [comment]
For now I put the commit in a separate branch, so people that download "master" can build it with old VS versions. 
When we can build it, then we will re-add it to the main branch.

**Pull request merged**
